name: Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run tests
        run: poetry run pytest
  publish:
    needs: [ test ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --without dev

      - name: Release to GH
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PyPI_TOKEN: ${{secrets.PYPI_TOKEN}}
        run: |
          pip install "python-semantic-release==9.3.1"
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release version && semantic-release publish
